on:
  # Trigger analysis when pushing to main or an existing pull requests.  Also trigger on
  # new pull requests
  push:
    branches:
      - main
  # pull_request:
  #     types: [opened, synchronize, reopened]
name: Contrast Security Scan
jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip source code
      run: zip -r output.zip . -x ".git/*" ".github/*"

    - name: Contrast Scan Action
      uses: Contrast-Security-OSS/contrastscan-action@v2.0.3
      with:
        artifact: output.zip
        apiKey: ${{ secrets.CONTRAST_API_KEY }}
        orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
        authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
        apiUrl: ${{ secrets.CONTRAST_API_URL }}
        projectName: inchcape-global-devsecops/poc-contrastsecurity
        language: javascript
        severity: high
        fail: true  
  
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif